// Receives a single-column table of hyperlinks as an argument and performs the steps below for each hyperlink

(hyperlink as text) as table =>

let
    Source = Web.BrowserContents(hyperlink),
    #"Extracted Table From Html" = Html.Table(Source, {{"Column1", ".col-xl-9 .bodyTextHeading5"}}),
    #"Split Column by Delimiter" = Table.SplitColumn(#"Extracted Table From Html", "Column1", Splitter.SplitTextByDelimiter(":", QuoteStyle.Csv), {"Column1.1", "Column1.2"}),
    #"Transposed Table" = Table.Transpose(#"Split Column by Delimiter"),
    #"Promoted Headers" = Table.PromoteHeaders(#"Transposed Table", [PromoteAllScalars=true]),
    #"Renamed Columns" = Table.RenameColumns(#"Promoted Headers",{{"Position Number", "Position ID"}}),
    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"Date Posted", type date}, {"Hiring Organization", type text}, {"Position ID", type text}, {"Job Title", type text}, {"Job Location", type text}, {"Work Model", type text}, {"Employment Type", type text}, {"Estimated Duration (In months)", Int64.Type}, {"Min Hourly Rate($)", Int64.Type}, {"Max Hourly Rate($)", Int64.Type}, {"Must Have Skills/Attributes", type text}})
in
    #"Changed Type"
